version: '3.9'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./etc/.env
    volumes:
      - '.:/devel'
    depends_on:
      - mysql
    networks:
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306", "--",
              "python", "manage.py", "runserver", "${API_LOCALHOST:-0.0.0.0}:${API_LOCALPORT:-5000}"]
    ports:
      - ${API_LOCALPORT:-5000}:${API_LOCALPORT:-5000}

  mysql:
    image: mariadb:10.5
    environment:
      - MYSQL_DATABASE=${DB_NAME:-_lenses}
      - MYSQL_USER=${DB_USER:-_lenses}
      - MYSQL_PASSWORD=${DB_PASSWORD:-0123456789}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - "mysql:/var/lib/mysql"
    networks:
      - mysql

volumes:
  mysql:

networks:
  mysql:
